name: PHP 8.0

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: PHP 8.0 syntax check
        uses: PrestaShopCorp/github-action-php-lint/8.0
