name: PHP 7.4

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: PHP 7.4 syntax check
        uses: prestashop/github-action-php-lint/7.4@v1
