name: PHP 8.3

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: PHP 8.3 syntax check
        uses: prestashop/github-action-php-lint/8.3@v1
