name: 5.4\u0020

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: PHP 5.4 syntax check
        uses: PrestaShopCorp/github-action-php-lint/5.4@master
