name: '5.6 '

on: [push, pull_request]

jobs:
  setup:
    name: Setup PHP
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@main
        with:
          php-version: '5.6'
          extensions: gd, curl

      - name: Lint main file
        run: php -l sig.php
